name: Meson

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CC: gcc
  CXX: g++

jobs:
  Cross_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install meson and ninja
        run: pip install meson ninja

      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libxi-dev mingw-w64

      - name: Install emscripten
        run: git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && sudo ./emsdk install latest && sudo ./emsdk activate latest && sudo ./emsdk_env.sh

      - name: Run web cross build
        run: ${{github.workspace}}/cross_web

      - name: Run Windows cross build
        run: rm -rf ${{github.workspace}}/builddir && ${{github.workspace}}/cross_linux2windows